//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalambury.KalamburyReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/KalamburyWcf")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nickField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nick {
            get {
                return this.nickField;
            }
            set {
                if ((object.ReferenceEquals(this.nickField, value) != true)) {
                    this.nickField = value;
                    this.RaisePropertyChanged("nick");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KalamburyReference.IKalamburyService", CallbackContract=typeof(Kalambury.KalamburyReference.IKalamburyServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IKalamburyService {
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IKalamburyService/wyslijPozycje", ReplyAction="http://tempuri.org/IKalamburyService/wyslijPozycjeResponse")]
        void wyslijPozycje(float x1, float y1, float x2, float y2);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IKalamburyService/wyslijPozycje", ReplyAction="http://tempuri.org/IKalamburyService/wyslijPozycjeResponse")]
        System.Threading.Tasks.Task wyslijPozycjeAsync(float x1, float y1, float x2, float y2);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IKalamburyService/pobierzRysujacego", ReplyAction="http://tempuri.org/IKalamburyService/pobierzRysujacegoResponse")]
        Kalambury.KalamburyReference.User pobierzRysujacego();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IKalamburyService/pobierzRysujacego", ReplyAction="http://tempuri.org/IKalamburyService/pobierzRysujacegoResponse")]
        System.Threading.Tasks.Task<Kalambury.KalamburyReference.User> pobierzRysujacegoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalamburyService/dolaczDoGry", ReplyAction="http://tempuri.org/IKalamburyService/dolaczDoGryResponse")]
        Kalambury.KalamburyReference.User dolaczDoGry(string nick);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalamburyService/dolaczDoGry", ReplyAction="http://tempuri.org/IKalamburyService/dolaczDoGryResponse")]
        System.Threading.Tasks.Task<Kalambury.KalamburyReference.User> dolaczDoGryAsync(string nick);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsInitiating=false, Action="http://tempuri.org/IKalamburyService/wyjdzZGry")]
        void wyjdzZGry(Kalambury.KalamburyReference.User uzytkownik);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsInitiating=false, Action="http://tempuri.org/IKalamburyService/wyjdzZGry")]
        System.Threading.Tasks.Task wyjdzZGryAsync(Kalambury.KalamburyReference.User uzytkownik);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IKalamburyService/pobierzUzytkownikow", ReplyAction="http://tempuri.org/IKalamburyService/pobierzUzytkownikowResponse")]
        System.Collections.Generic.List<Kalambury.KalamburyReference.User> pobierzUzytkownikow();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IKalamburyService/pobierzUzytkownikow", ReplyAction="http://tempuri.org/IKalamburyService/pobierzUzytkownikowResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Kalambury.KalamburyReference.User>> pobierzUzytkownikowAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsInitiating=false, Action="http://tempuri.org/IKalamburyService/wyczysc")]
        void wyczysc();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsInitiating=false, Action="http://tempuri.org/IKalamburyService/wyczysc")]
        System.Threading.Tasks.Task wyczyscAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsInitiating=false, Action="http://tempuri.org/IKalamburyService/wyslijWiadomosc")]
        void wyslijWiadomosc(Kalambury.KalamburyReference.User uzytkownik, string wiadomosc);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsInitiating=false, Action="http://tempuri.org/IKalamburyService/wyslijWiadomosc")]
        System.Threading.Tasks.Task wyslijWiadomoscAsync(Kalambury.KalamburyReference.User uzytkownik, string wiadomosc);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IKalamburyService/pobierzGrafike", ReplyAction="http://tempuri.org/IKalamburyService/pobierzGrafikeResponse")]
        byte[] pobierzGrafike();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IKalamburyService/pobierzGrafike", ReplyAction="http://tempuri.org/IKalamburyService/pobierzGrafikeResponse")]
        System.Threading.Tasks.Task<byte[]> pobierzGrafikeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKalamburyServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalamburyService/rysujPunkt")]
        void rysujPunkt(float x1, float y1, float x2, float y2);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalamburyService/dodajUzytkownika")]
        void dodajUzytkownika(Kalambury.KalamburyReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalamburyService/usunUzytkownika")]
        void usunUzytkownika(Kalambury.KalamburyReference.User user, System.Collections.Generic.List<Kalambury.KalamburyReference.User> uzytkownicy);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalamburyService/ustawHaslo")]
        void ustawHaslo(string name);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalamburyService/wyczyscObraz")]
        void wyczyscObraz();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalamburyService/wiadomosc")]
        void wiadomosc([System.ServiceModel.MessageParameterAttribute(Name="wiadomosc")] string wiadomosc1);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalamburyService/poprawnaOdp")]
        void poprawnaOdp();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKalamburyServiceChannel : Kalambury.KalamburyReference.IKalamburyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KalamburyServiceClient : System.ServiceModel.DuplexClientBase<Kalambury.KalamburyReference.IKalamburyService>, Kalambury.KalamburyReference.IKalamburyService {
        
        public KalamburyServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public KalamburyServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public KalamburyServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public KalamburyServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public KalamburyServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void wyslijPozycje(float x1, float y1, float x2, float y2) {
            base.Channel.wyslijPozycje(x1, y1, x2, y2);
        }
        
        public System.Threading.Tasks.Task wyslijPozycjeAsync(float x1, float y1, float x2, float y2) {
            return base.Channel.wyslijPozycjeAsync(x1, y1, x2, y2);
        }
        
        public Kalambury.KalamburyReference.User pobierzRysujacego() {
            return base.Channel.pobierzRysujacego();
        }
        
        public System.Threading.Tasks.Task<Kalambury.KalamburyReference.User> pobierzRysujacegoAsync() {
            return base.Channel.pobierzRysujacegoAsync();
        }
        
        public Kalambury.KalamburyReference.User dolaczDoGry(string nick) {
            return base.Channel.dolaczDoGry(nick);
        }
        
        public System.Threading.Tasks.Task<Kalambury.KalamburyReference.User> dolaczDoGryAsync(string nick) {
            return base.Channel.dolaczDoGryAsync(nick);
        }
        
        public void wyjdzZGry(Kalambury.KalamburyReference.User uzytkownik) {
            base.Channel.wyjdzZGry(uzytkownik);
        }
        
        public System.Threading.Tasks.Task wyjdzZGryAsync(Kalambury.KalamburyReference.User uzytkownik) {
            return base.Channel.wyjdzZGryAsync(uzytkownik);
        }
        
        public System.Collections.Generic.List<Kalambury.KalamburyReference.User> pobierzUzytkownikow() {
            return base.Channel.pobierzUzytkownikow();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Kalambury.KalamburyReference.User>> pobierzUzytkownikowAsync() {
            return base.Channel.pobierzUzytkownikowAsync();
        }
        
        public void wyczysc() {
            base.Channel.wyczysc();
        }
        
        public System.Threading.Tasks.Task wyczyscAsync() {
            return base.Channel.wyczyscAsync();
        }
        
        public void wyslijWiadomosc(Kalambury.KalamburyReference.User uzytkownik, string wiadomosc) {
            base.Channel.wyslijWiadomosc(uzytkownik, wiadomosc);
        }
        
        public System.Threading.Tasks.Task wyslijWiadomoscAsync(Kalambury.KalamburyReference.User uzytkownik, string wiadomosc) {
            return base.Channel.wyslijWiadomoscAsync(uzytkownik, wiadomosc);
        }
        
        public byte[] pobierzGrafike() {
            return base.Channel.pobierzGrafike();
        }
        
        public System.Threading.Tasks.Task<byte[]> pobierzGrafikeAsync() {
            return base.Channel.pobierzGrafikeAsync();
        }
    }
}
